replicaCount: 1
image:
  repository: ghcr.io/mikesmitty/kokoro-wyoming-tts
  tag: 0.5.1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 10210
onnxProvider: OpenVINOExecutionProvider
debug: false
extraArgs: []
resources: {}
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
persistence:
  enabled: true
  storageClass: ''
  accessMode: ReadWriteOnce
  size: 2Gi
  existingClaim: ''
nodeSelector: {}
tolerations: []
affinity: {}
podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch
imagePullSecrets: []
livenessProbe:
  enabled: true
  tcpSocket:
    port: wyoming
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
readinessProbe:
  enabled: true
  tcpSocket:
    port: wyoming
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
