apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama-intel.fullname" . }}-ollama
  labels:
    {{- include "ollama-intel.ollama.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
  - port: {{ .Values.ollama.service.port }}
    targetPort: ollama
    protocol: TCP
    name: ollama
  selector:
    {{- include "ollama-intel.ollama.selectorLabels" . | nindent 4 }}
