apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ollama-intel.fullname" . }}-ollama
  labels:
    {{- include "ollama-intel.ollama.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ollama.replicaCount }}
  selector:
    matchLabels:
      {{- include "ollama-intel.ollama.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ollama-intel.ollama.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: ollama
        {{- if .Values.ollama.image.repository }}
        image: "{{ .Values.ollama.image.repository }}:{{ .Values.ollama.image.tag }}"
        {{- else }}
        # Note: This chart expects a pre-built image or manual build
        # Build the image from charts/ollama-intel/docker/Dockerfile
        image: "ollama-intel:{{ .Values.ollama.image.tag }}"
        {{- end }}
        imagePullPolicy: {{ .Values.ollama.image.pullPolicy }}
        ports:
        - name: ollama
          containerPort: {{ .Values.ollama.service.port }}
          protocol: TCP
        env:
        {{- range $key, $value := .Values.ollama.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- with .Values.ollama.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.ollama.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.ollama.livenessProbe.httpGet.path }}
            port: {{ .Values.ollama.livenessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.ollama.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.ollama.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.ollama.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.ollama.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.ollama.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.ollama.readinessProbe.httpGet.path }}
            port: {{ .Values.ollama.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.ollama.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.ollama.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.ollama.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.ollama.readinessProbe.failureThreshold }}
        {{- end }}
        {{- with .Values.ollama.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.ollama.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.ollama.persistence.enabled }}
        - name: ollama-data
          mountPath: {{ .Values.ollama.persistence.mountPath }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.ollama.persistence.enabled }}
      - name: ollama-data
        persistentVolumeClaim:
          claimName: {{ .Values.ollama.persistence.existingClaim | default (printf "%s-ollama-data" (include "ollama-intel.fullname" .)) }}
      {{- end }}
