{{- if and .Values.webui.enabled .Values.webui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ollama-intel.fullname" . }}-webui
  labels:
    {{- include "ollama-intel.webui.labels" . | nindent 4 }}
  {{- with .Values.webui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.webui.ingress.className }}
  ingressClassName: {{ .Values.webui.ingress.className }}
  {{- end }}
  {{- if .Values.webui.ingress.tls }}
  tls:
    {{- range .Values.webui.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.webui.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "ollama-intel.fullname" $ }}-webui
                port:
                  number: {{ $.Values.webui.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
