name: Ollama Upstream Vulkan Image

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-ollama-upstream.yaml"
      - "charts/ollama-intel/Chart.yaml"
  schedule:
    # Rebuild monthly to get updates
    - cron: "0 0 1 * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mikesmitty/ollama-vulkan

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract Ollama version from Chart.yaml
        id: ollama-version
        run: |
          OLLAMA_VERSION=$(awk '/^appVersion:/ {print $2}' charts/ollama-intel/Chart.yaml | tr -d '"')
          echo "version=v${OLLAMA_VERSION}" >> $GITHUB_OUTPUT
          echo "version_short=${OLLAMA_VERSION}" >> $GITHUB_OUTPUT
          echo "Building Ollama version: v${OLLAMA_VERSION}"

      - name: Clone ollama repository
        run: |
          git clone --depth 1 --branch ${{ steps.ollama-version.outputs.version }} https://github.com/ollama/ollama.git ollama-src
          echo "Cloned ollama at ${{ steps.ollama-version.outputs.version }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.ollama-version.outputs.version_short }}
            type=raw,value=${{ steps.ollama-version.outputs.version }}
            type=raw,value=${{ steps.ollama-version.outputs.version_short }}-{{date 'YYYYMMDD'}}
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ollama-src
          file: ollama-src/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Output image details
        run: |
          echo "Image built and pushed successfully"
          echo "Ollama version: ${{ steps.ollama-version.outputs.version }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo ""
          echo "This image uses the upstream Ollama Vulkan Dockerfile"
          echo "User: ubuntu (UID 1000)"
          echo "Model storage: /home/ubuntu/.ollama"
