name: Ollama Intel GPU Image

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-ollama-intel.yaml"
      - "charts/ollama-intel/docker/**"
  schedule:
    # Rebuild monthly to get updates
    - cron: "0 0 1 * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mikesmitty/ollama-intel-gpu

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract appVersion
        id: app-version
        run: |
          APP_VERSION=$(awk '/^appVersion:/ {print $2}' charts/ollama-intel/Chart.yaml | tr -d '"')
          echo "version=${APP_VERSION}" >> $GITHUB_OUTPUT
          echo "App version: ${APP_VERSION}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.app-version.outputs.version }}
            type=raw,value=${{ steps.app-version.outputs.version }}-{{date 'YYYYMMDD'}}
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: charts/ollama-intel/docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Output image details
        run: |
          echo "Image built and pushed successfully"
          echo "App version: ${{ steps.app-version.outputs.version }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Build args use defaults from Dockerfile"
